repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: fix-byte-order-marker
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        # args: ["-d {extends: relaxed, rules: {line-length: {max: 120}}}"]
        args: ["-c", ".yamllint.cfg"]
        # verbose: true
        # entry: bash -c 'yamllint "$@" || true' --

-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint