---
name: Build and Deploy the lambda code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  AWS_REGION: ca-central-1
  BUCKET_NAME: sai-ts-learn-tf

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Hello Here
        run: |
          echo "Hi here"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check the code quality using pre-commit hook
        run: |
          pre-commit run --all-files --verbose

  deploy-dev:
    runs-on: "ubuntu-latest"
    environment: "dev"
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Dev Build Code
        run: |
          sh +x build_using_github.sh

  deploy-prod:
    runs-on: "ubuntu-latest"
    environment: "prod"
    needs: [build, deploy-dev]
    steps:
      # Download published artifact
      - uses: actions/checkout@v3

      - name: Prod Build Code
        run: |
          sh +x build_using_github.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy the Zip file to AWS S3
        run: |
          echo `pwd`
          echo `ls`
          echo `ls build_code`
          aws s3 cp build_code/github_archive.zip s3://sai-ts-learn-tf/code/lambda/zip/

      - name: Delete the existing files in S3
        run: |
          aws s3 rm s3://sai-ts-learn-tf/github_archive/download/ --recursive

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
                --function-name  github_archive \
                --s3-bucket sai-ts-learn-tf \
                --s3-key code/lambda/zip/github_archive.zip
---
