
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and deploy the lambda code using docker image (ECR).

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  AWS_REGION: ca-central-1 # set this to your preferred AWS region, e.g. us-west-1

permissions:
  contents: read

jobs:
  check-code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pre-commit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check Code quality using pre-commit
        run: |
          pre-commit run --all-files --verbose

  deploy-lambda-ecr-code-prod:
    runs-on: "ubuntu-latest"
    environment: "prod"
    needs: [check-code-quality]
    steps:
      # Download published artifact
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create ECR image and Push the image to ECR
        run: |
          aws ecr get-login-password \
                --region ca-central-1 | docker login --username AWS \
                --password-stdin 000549131923.dkr.ecr.ca-central-1.amazonaws.com

          docker build -t github_archive_sai .

          docker tag github_archive_sai:latest \
                000549131923.dkr.ecr.ca-central-1.amazonaws.com/github_archive_sai:latest

          docker push 000549131923.dkr.ecr.ca-central-1.amazonaws.com/github_archive_sai:latest


      - name: Delete the existing data files in S3
        run: |
          aws s3 rm s3://sai-ts-learn-tf/github_archive/download/ --recursive

      - name: Deploy to AWS Lambda by updating the ecr image
        run: |
          aws lambda update-function-code \
                --function-name  github-archive-docker-application \
                --image-uri 000549131923.dkr.ecr.ca-central-1.amazonaws.com/github_archive_sai:latest
